// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Printf from "bs-platform/lib/es6/printf.js";
import * as Immutable_bytes from "./immutable_bytes.mjs";

var addr1 = /* Byte_address */{
  _0: 1
};

var bytes_a = Immutable_bytes.make("Hello world");

var bytes_b = Immutable_bytes.write_byte(bytes_a, addr1, 65);

var b_a = Immutable_bytes.read_byte(bytes_a, addr1);

var b_b = Immutable_bytes.read_byte(bytes_b, addr1);

Curry._2(Printf.printf(/* Format */{
          _0: {
            TAG: /* Int */4,
            _0: /* Int_d */0,
            _1: /* No_padding */0,
            _2: /* No_precision */0,
            _3: {
              TAG: /* Char_literal */12,
              _0: /* ' ' */32,
              _1: {
                TAG: /* Int */4,
                _0: /* Int_d */0,
                _1: /* No_padding */0,
                _2: /* No_precision */0,
                _3: {
                  TAG: /* Char_literal */12,
                  _0: /* '\n' */10,
                  _1: /* End_of_format */0
                }
              }
            }
          },
          _1: "%d %d\n"
        }), b_a, b_b);

export {
  
}
/* bytes_a Not a pure module */
