// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Map from "bs-platform/lib/es6/map.js";
import * as Caml_obj from "bs-platform/lib/es6/caml_obj.js";

var compare = Caml_obj.caml_compare;

var IntMap = $$Map.Make({
      compare: compare
    });

export {
  IntMap ,
  
}
/* IntMap Not a pure module */
